name: fl_toast
description: Easy Toast library for flutter
version: 1.0.0
repository: https://github.com/bdlukaa/fl_toast

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
